version: "3.8"
services: 
  matrix-synapse:
    image: matrixdotorg/synapse:latest
    ports: 
      - "8008:8008"
    environment:
      - SYNAPSE_SERVER_NAME=vm1
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_CONFIG_PATH=/config/homeserver.yaml
      - UID=0
      - GID=0
    volumes:
      - "./config:/config:rw"
      - "./data:/data:rw"       